### PR TITLE
feat: remove unnecessary docs from targeting packs

### PR DESCRIPTION
**Pull request by oleksandr-didyk**
Resolves https://github.com/dotnet/source-build/issues/2902

Removed all `.xml` docs for SBRP targeting packs with the exception of `NetStandard.Library.Ref/2.1.0` (see linked GitHub issue for more info).

List of all removed files can be found here (for quicker and easier reference) -> [TargetPackDocsRemoved.txt](https://github.com/dotnet/source-build-reference-packages/files/9141776/TargetPackDocsRemoved.txt)

### CODE REVIEW

**Comment by crummel** [comment]
Have you verified that the final source-built SDK looks the same after this change?  If so this looks good to me.

**Comment by MichaelSimons** [comment]
I have the same comment as @crummel, looks good but we do need to verify this in a full tarball build.

**Comment by oleksandr-didyk** [comment]
Will verify the resulting tarball and will update the PR once its A-OK

**Comment by oleksandr-didyk** [comment]
Verified the final source-build SDK ([version used](https://github.com/dotnet/installer/tree/53587f98e132f3c5bc6d2a77d779d6872710d53e)), `.xml` doc files are excluded, everything else seems to be intact and functional

**Review by MichaelSimons — APPROVED** [review]
Thanks!

**Pull request merged**
