### PR TITLE
Remove SBRP solution file

### PR DESCRIPTION
**Pull request by Winniexu01**
Fixes https://github.com/dotnet/source-build/issues/4716

This solution file is added by https://github.com/dotnet/source-build-reference-packages/pull/1036. It seems unnecessary, so I removed it.

### CODE REVIEW

**Comment by Winniexu01** [comment]
Here is the [SBRP example pipeline run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2577803&view=results) (internal Microsoft link)

**Review by mthalman — APPROVED** [review]

**Comment by Winniexu01** [comment]
Hi @mthalman, should I backport this to Release/9.0?

**Comment by mthalman** [comment]
> Hi @mthalman, should I backport this to Release/9.0?

I don't think that will be necessary. Agree, @MichaelSimons?

**Comment by MichaelSimons** [comment]
> > Hi @mthalman, should I backport this to Release/9.0?
> 
> I don't think that will be necessary. Agree, @MichaelSimons?

I agree, the ROI doesn't justify the work.

**Pull request merged**
