### PR TITLE
System.Security.Cryptography.Xml - add 4.7.1 and remove 4.7.0

### PR DESCRIPTION
**Pull request by NikolaMilosavljevic**
Fixes: https://github.com/dotnet/source-build/issues/3082

### CODE REVIEW

**Comment by MichaelSimons** [comment]
@NikolaMilosavljevic - Can you also fix the other CG - https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-source-build-reference-packages?_a=alerts&typeId=6439730&alerts-view-option=active (Microsoft internal link)?  I mentioned it subtly in the issue, I should have been more explicit.

**Review by MichaelSimons — COMMENTED** [review]
You will need to add a DependencyPackageProjects entry in eng/build.props like [this](https://github.com/dotnet/source-build-reference-packages/blob/release/6.0/eng/Build.props#L18) for the new package.

**Comment by NikolaMilosavljevic** [comment]
> @NikolaMilosavljevic - Can you also fix the other CG - https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-source-build-reference-packages?_a=alerts&typeId=6439730&alerts-view-option=active (Microsoft internal link)? I mentioned it subtly in the issue, I should have been more explicit.

Sure, I'll add a change for the other package (System.Drawing.Common) - would same PR be OK?

**Comment by NikolaMilosavljevic** [comment]
> You will need to add a DependencyPackageProjects entry in eng/build.props like [this](https://github.com/dotnet/source-build-reference-packages/blob/release/6.0/eng/Build.props#L18) for the new package.

I see, updating this now.

**Comment by MichaelSimons** [comment]
> Sure, I'll add a change for the other package (System.Drawing.Common) - would same PR be OK?

I think so.

**Comment by NikolaMilosavljevic** [comment]
There's a pipeline error about missing usage in baseline:

```
2022-10-28T02:05:19.7521372Z ##[error].packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22524.5/tools/SourceBuild/AfterSourceBuild.proj(65,5): error : (NETCORE_ENGINEERING_TELEMETRY=AfterSourceBuild) 1 new packages used not in baseline! See report at /__w/1/s/artifacts/source-build/self/prebuilt-report/baseline-comparison.xml for more information. Package IDs are:
System.Security.Cryptography.Xml.4.7.1
2022-10-28T02:05:19.7532508Z   Prebuilt usages are different from the baseline found at '/__w/1/s/eng/SourceBuildPrebuiltBaseline.xml'. If it's acceptable to update the baseline, copy the contents of the automatically generated baseline '/__w/1/s/artifacts/source-build/self/prebuilt-report/generated-new-baseline.xml'.
```

@MichaelSimons , I prepared the change to update the baseline, but wanted to double-check if this is needed, or should a different change be made?

**Comment by MichaelSimons** [comment]
> @MichaelSimons , I prepared the change to update the baseline, but wanted to double-check if this is needed, or should a different change be made?

This is a symptom of not having the DependencyPackageProjects entry.  I would expect CI to pass now that it was added with your latest commit.

**Comment by NikolaMilosavljevic** [comment]
> > @MichaelSimons , I prepared the change to update the baseline, but wanted to double-check if this is needed, or should a different change be made?
> 
> This is a symptom of not having the DependencyPackageProjects entry. I would expect CI to pass now that it was added with your latest commit.

My local build was still experiencing the same issue even with DependencyPackageProjects change, but I see that all checks are now green.

**Comment by NikolaMilosavljevic** [comment]
> > Sure, I'll add a change for the other package (System.Drawing.Common) - would same PR be OK?
> 
> I think so.

I'll create a new PR for the other issue, to not delay merge of this one.

**Comment by MichaelSimons** [comment]
> My local build was still experiencing the same issue even with DependencyPackageProjects change, but I see that all checks are now green.

Guessing here that this is a  symptom of not cleaning after the initial build which pulled the external package into your local package cache.

**Review by MichaelSimons — APPROVED** [review]

**Pull request merged**
