### PR TITLE
Add SBRPs to enable PVP flow for templating repo

### PR DESCRIPTION
**Pull request by mthalman**
Adds the following packages:

* NuGet.Common.6.5.0
* NuGet.Configuration.6.5.0
* NuGet.Credentials.6.5.0
* NuGet.Frameworks.6.5.0
* NuGet.Packaging.6.5.0
* NuGet.Protocol.6.5.0
* NuGet.Versioning.6.5.0

This required manual workarounds for https://github.com/dotnet/source-build/issues/3364 and https://github.com/dotnet/sdk/issues/31655.

Contributes to https://github.com/dotnet/source-build/issues/3043

### CODE REVIEW

**Comment by MichaelSimons** [comment]
Is there a reason why templating can't be on the latest version of NuGet?

**Comment by mthalman** [comment]
> Is there a reason why templating can't be on the latest version of NuGet?

Good question. The templating repo currently has the version managed by dependabot: https://github.com/dotnet/templating/blob/985dfbb1fe2e578dd70f5923600093e668e49327/eng/dependabot/Packages.props#L15-L17

It was being overriden by source-build with this configuration: https://github.com/dotnet/templating/blob/985dfbb1fe2e578dd70f5923600093e668e49327/eng/Package.props#L17-L19

But with the PVP changes, those versions don't get applied here, so we're left with the default.

**Comment by mthalman** [comment]
Closing this in preference to the changes in https://github.com/dotnet/templating/pull/6360.

**Comment by mthalman** [comment]
Reopening this instead of using the changes in https://github.com/dotnet/templating/pull/6360 because [templating requires that preview versions of the `NuGet.*` packages be available on nuget.org](https://github.com/dotnet/templating/pull/6360#issuecomment-1503877087).

**Review by MichaelSimons — APPROVED** [review]

**Review by mmitche — APPROVED** [review]

**Comment by mmitche** [comment]
I agree with this. Generally, when I see use of stable package versions, and I know that these aren't being used for functionality in the build or being re-disted (e.g. Microsoft.NET.Compilers.Toolset), I think they are good candidates for SBRP.

**Pull request merged**
