### PR TITLE
Add text-only Microbuild packages

### PR DESCRIPTION
**Pull request by crummel**

### CODE REVIEW

**Review by dagood — APPROVED** [review]

**Review by dseefeld — APPROVED** [review]
Do we want these in master or pre-arcade?

**Comment by crummel** [comment]
Both, probably, right?  I can make another quick PR to port these to pre-arcade.

**Comment by dseefeld** [comment]
> Both, probably, right? I can make another quick PR to port these to pre-arcade.

The pre-arcade branch is what is used in source-build master.

**Comment by crummel** [comment]
Opened https://github.com/dotnet/source-build-reference-packages/pull/173 for pre-arcade.

**Pull request merged**
