### PR TITLE
System.Text.Json 7.0.3

### PR DESCRIPTION
**Pull request by rainersigwald**
Followed the README to add STJ 7.0.3

* `./generate.sh --package System.Text.Json,7.0.3`
* revert modified files
* Fix build errors the same way STJ 7.0.2 did

### CODE REVIEW

**Comment by Forgind** [comment]
I got most of the way through making my own PR before I noticed you'd made this one.

Looks mostly the same as what I would've made, but I also added S.T.J to eng\Build.props. It's in the readme. Did you miss it, or did you intentionally skip it, and if the latter, why?

**Comment by rainersigwald** [comment]
STJ 7.0.2 was not there and it didn't seem to be required (https://dev.azure.com/dnceng-public/public/_build/results?buildId=348238&view=logs&j=2f0d093c-1064-5c86-fc5b-b7b1eca8e66a&t=d2b639a6-cb19-5f1f-66fd-8047f66b3026&l=1861). But I don't really understand why, that definitely tripped me up.

**Comment by mthalman** [comment]
> STJ 7.0.2 was not there and it didn't seem to be required (https://dev.azure.com/dnceng-public/public/_build/results?buildId=348238&view=logs&j=2f0d093c-1064-5c86-fc5b-b7b1eca8e66a&t=d2b639a6-cb19-5f1f-66fd-8047f66b3026&l=1861). But I don't really understand why, that definitely tripped me up.

It does need to be listed there. New packages need to be listed there. Once a .NET release occurs and we can self-reference the latest version of the SBRP package, then we can clean up old references (see https://github.com/dotnet/source-build-reference-packages/pull/745). That's why 7.0.2 isn't listed.

**Comment by rainersigwald** [comment]
Ok. Done.

**Review by mthalman — APPROVED** [review]

**Comment by Forgind** [comment]
As far as where in the Build.props, the readme said "dependency order." I'm not aware of any dependencies among the packages in that list, so I don't think its placement matters, and being on bottom is fine. Is that what you were thinking, too?

**Comment by mthalman** [comment]
> As far as where in the Build.props, the readme said "dependency order." I'm not aware of any dependencies among the packages in that list, so I don't think its placement matters, and being on bottom is fine. Is that what you were thinking, too?

That's relevant when dependent projects get generated by the tool. So if STJ had dependencies which weren't already included in SBRP, the tool would generate projects for those. The whole set of those package names need to be listed in Build.props in dependency order.

**Pull request merged**
