### PR TITLE
Add Microsoft.Extensions.Logging.Abstractions 6.0.4 ref pack

### PR DESCRIPTION
**Pull request by hoyosjs**

### CODE REVIEW

**Comment by mthalman** [comment]
What is the reason for adding this? Just want to make sure it's necessary.

**Review by mthalman — COMMENTED** [review]
The changes to interopservices should be reverted.

Also, please follow the [workflow](https://github.com/dotnet/source-build-reference-packages?tab=readme-ov-file#workflow) instructions for updating the eng/Build.props file.

**Comment by hoyosjs** [comment]
> Also, please follow the [workflow](https://github.com/dotnet/source-build-reference-packages?tab=readme-ov-file#workflow) instructions for updating the eng/Build.props file. 

I was looking at that one, was just trying to see why the other logging abstractions package is not in build.props.

> The changes to interopservices should be reverted.

Yes, sorry. I missed the comments and thought the tool had been updated so it fell under the second camp.

> What is the reason for adding this? Just want to make sure it's necessary.

It comes as a suggestion in https://github.com/dotnet/diagnostics/pull/4296

**Review by mthalman — APPROVED** [review]

**Comment by hoyosjs** [comment]
@mthalman feel free to merge if it looks good. I lack merge rights

**Pull request merged**
