### PR TITLE
Remove netcoreapp2.1 artifacts and support

### PR DESCRIPTION
**Pull request by MichaelSimons**
Fixes https://github.com/dotnet/source-build/issues/3445

### CODE REVIEW

**Comment by MichaelSimons** [comment]
cc @ViktorHofer - FYI

**Review by mthalman — APPROVED** [review]

**Comment by MichaelSimons** [comment]
This requires https://github.com/dotnet/runtime/pull/84782 to be merged first.

**Comment by ViktorHofer** [comment]
Isn't https://github.com/dotnet/runtime/pull/84782 blocked on https://github.com/dotnet/runtime/pull/86151?

**Comment by MichaelSimons** [comment]
> Isn't [dotnet/runtime#84782](https://github.com/dotnet/runtime/pull/84782) blocked on [dotnet/runtime#86151](https://github.com/dotnet/runtime/pull/86151)?

I don't think so.  Because the tip of runtime doesn't have prebuilt detection enabled, there is no dependency.  In the full product build, the SBRP version from installer is what gets used.

**Comment by ViktorHofer** [comment]
Sorry but I still don't understand what I need to do in the PR to make it ready to be merged. Do I just need to add the SBRP package feed?

**Comment by MichaelSimons** [comment]
> Sorry but I still don't understand what I need to do in the PR to make it ready to be merged. Do I just need to add the SBRP package feed?

Let's discuss in the PR instead of here.

**Comment by ViktorHofer** [comment]
Just merged the runtime PR in. This should now be unblocked.

**Pull request merged**
