### PR TITLE
[release/8.0] Revert "Add xunit abstractions 2.0.3 (#755)" (#784)

### PR DESCRIPTION
**Pull request by mmitche**
This reverts commit 67acd4b5edead3ecbb6b4a99ad923751705cf73c.

### CODE REVIEW

**Comment by mmitche** [comment]
Hold on merging this. I think this may break the VMR online build due to prebuilt detection. Want to check first.

**Comment by ViktorHofer** [comment]
I assume you are reverting this change as we don't need that package in favor of arcade's XUnitAssert fork?

**Comment by mmitche** [comment]
Nope. I was thinking this would be an easy way to get this package so it could be used in xunit in source build externals. It has no implementation. But it IS loaded at runtime.

**Comment by mmitche** [comment]
Verified in VMR build.

**Review by ViktorHofer — APPROVED** [review]

**Pull request merged**
