### PR TITLE
Add Microsoft.CodeAnalysis 3.11.0 SB package dependencies

### PR DESCRIPTION
**Pull request by mavasani**
Required for https://github.com/dotnet/roslyn-analyzers/pull/6701, which moves the analyzer packages in that repo to Microsoft.CodeAnalysis 3.11.0.

- I tried to follow the steps here: https://github.com/mavasani/source-build-reference-packages#adding-new-packages.
- However, the third step to run `./build.sh -sb` executed and exited very quickly, not sure if it completed fine or failed.
- I also did not do anything for `Revert changes for packages that were already existed in the repository`, as I presume existing 3.3.1 references would still be needed for the repo to build until https://github.com/dotnet/roslyn-analyzers/pull/6701 goes in.

### CODE REVIEW

**Comment by mavasani** [comment]
The PR build failed.. @MichaelSimons can you please help me with taking this PR ahead?

**Comment by MichaelSimons** [comment]
> The PR build failed.. @MichaelSimons can you please help me with taking this PR ahead?

I would recommend reverting all changes to existing packages.  This is called out in the [suggested Workflow](https://github.com/dotnet/source-build-reference-packages#workflow).  There are some packages with customization that get overridden when regenerating.  Also the new projects added to the build.props should be added at the bottom of the list.

**Comment by mavasani** [comment]
> I would recommend reverting all changes to existing packages. 

@MichaelSimons I wasn’t sure what reverting meant here. Is there a specific commit that I need to revert? Note that I am not removing any existing packages as part of that PR, just adding new ones. Do we still need to revert stuff? If you don’t mind, can you please help me with that PR and push the required revert?

**Comment by MichaelSimons** [comment]
> I wasn’t sure what reverting meant here. 

It means after you run the generate command, you revert/don't commit any of the existing packages that were re-generated.  After you check them in, it gets a bit harder to undo this.

**Comment by mavasani** [comment]
> > I wasn’t sure what reverting meant here.
> 
> It means after you run the generate command, you revert/don't commit any of the existing packages that were re-generated. After you check them in, it gets a bit harder to undo this.

Ah, thanks for the explanation. I’ll do so and update the PR. Thanks!

**Comment by MichaelSimons** [comment]
I pushed some updates.

**Comment by mmitche** [comment]
@mavasani the build failure is due to https://github.com/dotnet/sdk/issues/33042 and will need to be manually resolved. I think this commit basically contains all the changes you need to make: https://github.com/dotnet/source-build-reference-packages/commit/07b2c718295127ff6ce5fcbe10dd8f600f32166a

**Comment by MichaelSimons** [comment]
I pushed some fixes.  The build passes locally for me now.

**Review by MichaelSimons — APPROVED** [review]

**Pull request merged**
