### PR TITLE
Remove unreferenced packages

### PR DESCRIPTION
**Pull request by MichaelSimons**
The following SBRPs were detected as not being referenced in the product source-build and therefore are being removed:

microsoft.bcl.asyncinterfaces/1.0.0
microsoft.bcl.asyncinterfaces/1.1.0
microsoft.build.framework/16.0.461
microsoft.build.framework/16.10.0
microsoft.build.framework/17.3.2
microsoft.build.tasks.core/16.10.0
microsoft.build.tasks.core/17.3.2
microsoft.build.utilities.core/16.0.461
microsoft.build.utilities.core/16.10.0
microsoft.build.utilities.core/17.3.2
microsoft.build/16.10.0
microsoft.build/17.3.2
microsoft.codeanalysis.common/3.3.1
microsoft.codeanalysis.common/3.7.0
microsoft.codeanalysis.common/4.5.0
microsoft.codeanalysis.common/4.6.0
microsoft.codeanalysis.csharp.workspaces/3.3.1
microsoft.codeanalysis.csharp.workspaces/3.7.0
microsoft.codeanalysis.csharp.workspaces/4.0.1
microsoft.codeanalysis.csharp/3.3.1
microsoft.codeanalysis.csharp/3.7.0
microsoft.codeanalysis.csharp/4.5.0
microsoft.codeanalysis.csharp/4.6.0
microsoft.codeanalysis.visualbasic.workspaces/3.3.1
microsoft.codeanalysis.visualbasic.workspaces/3.7.0
microsoft.codeanalysis.visualbasic/3.3.1
microsoft.codeanalysis.visualbasic/3.7.0
microsoft.codeanalysis.workspaces.common/3.3.1
microsoft.codeanalysis.workspaces.common/3.7.0
microsoft.codeanalysis.workspaces.common/4.0.1
microsoft.extensions.configuration.abstractions/2.1.1
microsoft.extensions.configuration.abstractions/6.0.0
microsoft.extensions.configuration.binder/2.1.1
microsoft.extensions.configuration.binder/6.0.0
microsoft.extensions.configuration/2.1.1
microsoft.extensions.configuration/6.0.0
microsoft.extensions.dependencyinjection.abstractions/2.1.1
microsoft.extensions.dependencyinjection.abstractions/6.0.0
microsoft.extensions.dependencyinjection.abstractions/7.0.0
microsoft.extensions.dependencyinjection/6.0.0
microsoft.extensions.dependencyinjection/7.0.0
microsoft.extensions.dependencymodel/3.0.0
microsoft.extensions.filesystemglobbing/2.0.0
microsoft.extensions.filesystemglobbing/7.0.0
microsoft.extensions.logging.abstractions/2.1.1
microsoft.extensions.logging.abstractions/6.0.0
microsoft.extensions.logging.abstractions/7.0.0
microsoft.extensions.logging.abstractions/7.0.1
microsoft.extensions.logging.configuration/6.0.0
microsoft.extensions.logging.console/6.0.0
microsoft.extensions.logging/2.1.1
microsoft.extensions.logging/6.0.0
microsoft.extensions.logging/7.0.0
microsoft.extensions.options.configurationextensions/6.0.0
microsoft.extensions.options/2.1.1
microsoft.extensions.options/6.0.0
microsoft.extensions.options/7.0.0
microsoft.extensions.primitives/2.1.1
microsoft.extensions.primitives/7.0.0
microsoft.net.stringtools/1.0.0
microsoft.net.stringtools/17.3.2
microsoft.win32.systemevents/8.0.0
nuget.commands/6.2.4
nuget.commands/6.7.1
nuget.common/6.2.4
nuget.common/6.7.1
nuget.configuration/6.2.4
nuget.configuration/6.7.1
nuget.credentials/6.2.4
nuget.credentials/6.7.1
nuget.dependencyresolver.core/6.2.4
nuget.dependencyresolver.core/6.7.1
nuget.frameworks/6.2.4
nuget.frameworks/6.7.1
nuget.librarymodel/6.2.4
nuget.librarymodel/6.7.1
nuget.packaging/6.2.4
nuget.packaging/6.7.1
nuget.projectmodel/6.2.4
nuget.projectmodel/6.7.1
nuget.protocol/6.2.4
nuget.protocol/6.7.1
nuget.versioning/6.2.4
nuget.versioning/6.7.1
system.componentmodel.composition/7.0.0
system.configuration.configurationmanager/4.7.0
system.data.sqlclient/4.8.5
system.diagnostics.diagnosticsource/6.0.0
system.diagnostics.diagnosticsource/7.0.0
system.diagnostics.diagnosticsource/7.0.2
system.drawing.common/8.0.0
system.io.hashing/8.0.0
system.io.pipelines/6.0.3
system.io.pipelines/7.0.0
system.io.pipelines/8.0.0
system.memory/4.5.1
system.net.http/4.3.4
system.reflection.metadata/1.4.2
system.reflection.metadata/6.0.1
system.reflection.metadataloadcontext/8.0.0
system.reflection.typeextensions/4.4.0
system.reflection.typeextensions/4.7.0
system.runtime.compilerservices.unsafe/4.5.0
system.runtime.compilerservices.unsafe/4.5.1
system.runtime.compilerservices.unsafe/4.6.0
system.runtime.compilerservices.unsafe/4.7.0
system.runtime.extensions/4.3.1
system.runtime/4.3.1
system.security.cryptography.cng/4.3.0
system.security.cryptography.csp/4.3.0
system.security.cryptography.openssl/4.3.0
system.security.cryptography.pkcs/5.0.0
system.security.cryptography.protecteddata/4.7.0
system.text.encoding.codepages/8.0.0
system.text.encodings.web/4.6.0
system.text.encodings.web/4.7.0
system.text.json/4.6.0
system.text.json/4.7.0
system.text.json/7.0.2
system.threading.channels/6.0.0
system.threading.channels/8.0.0
system.threading.tasks.dataflow/8.0.0
system.threading.tasks.extensions/4.5.2
system.threading.tasks.extensions/4.5.3

### CODE REVIEW

**Comment by MichaelSimons** [comment]
e2e validation is currently blocked on a failing Stage 2 build - https://github.com/dotnet/source-build/issues/4494#issuecomment-2215253333

**Comment by ViktorHofer** [comment]
Stage2 is now unblocked :)

**Comment by MichaelSimons** [comment]
This is ready for review.  It was validated with a Lite SB build in https://github.com/dotnet/sdk/pull/42028.

**Review by ViktorHofer — APPROVED** [review]

**Review by mthalman — APPROVED** [review]

**Comment by lewing** [comment]
This is breaking the runtime build see https://github.com/dotnet/runtime/pull/104856

**Comment by MichaelSimons** [comment]
> This is breaking the runtime build see [dotnet/runtime#104856](https://github.com/dotnet/runtime/pull/104856)

Replied at https://github.com/dotnet/runtime/pull/104856/files#r1688066029

**Pull request merged**
