### PR TITLE
Add xUnit.2.6.1

### PR DESCRIPTION
**Pull request by ellahathaway**
Resolves arcade related prebuilts https://github.com/dotnet/source-build/issues/3813 and https://github.com/dotnet/source-build/issues/3665

(Build related to v2.5.3, but arcade has recently updated to v2.6.1. Once arcade SDK is updated, the version will match the added SBRP).

**Leaving as a draft due to the following build errors**:

```
Restored /root/repos/source-build-reference-packages/artifacts/sb/src/src/referencePackages/src/xunit.abstractions/2.0.3/xunit.abstractions.2.0.3.csproj (in 108 ms).
  /root/repos/source-build-reference-packages/artifacts/sb/package-cache/microsoft.dotnet.arcade.sdk/9.0.0-beta.23628.1/tools/StrongName.targets(89,5): error : PublicKey, PublicKeyToken and AssemblyOriginatorKeyFile must be specified [/root/repos/source-build-reference-packages/artifacts/sb/src/src/referencePackages/src/xunit.abstractions/2.0.3/xunit.abstractions.2.0.3.csproj::TargetFramework=netstandard2.0] [/root/.nuget/packages/microsoft.dotnet.arcade.sdk/9.0.0-beta.23628.1/tools/Build.proj]
  /root/repos/source-build-reference-packages/artifacts/sb/package-cache/microsoft.dotnet.arcade.sdk/9.0.0-beta.23628.1/tools/StrongName.targets(89,5): error : PublicKey, PublicKeyToken and AssemblyOriginatorKeyFile must be specified [/root/repos/source-build-reference-packages/artifacts/sb/src/src/referencePackages/src/xunit.abstractions/2.0.3/xunit.abstractions.2.0.3.csproj::TargetFramework=netstandard1.0] [/root/.nuget/packages/microsoft.dotnet.arcade.sdk/9.0.0-beta.23628.1/tools/Build.proj]
```

### CODE REVIEW

**Comment by ellahathaway** [comment]
@ViktorHofer - Saw that you responded to a different issue about generating SBRPs, so I'm wondering if you know whether these errors are related to a step that I missed in generation? Let me know if you're not the correct person to ping about this issue. TIA!

**Comment by mthalman** [comment]
@MichaelSimons or @mmitche - Do we know how Arcade took dependencies on new versions of xUnit in the past? It has an existing dependency today that never required an update to SBRP.

**Comment by MichaelSimons** [comment]
> @MichaelSimons or @mmitche - Do we know how Arcade took dependencies on new versions of xUnit in the past? It has an existing dependency today that never required an update to SBRP.

The projects which bring in these dependencies were never part of SB before.  Looks like https://github.com/dotnet/arcade/pull/14320 changed this and it looks like it wasn't intentional.

**Comment by MichaelSimons** [comment]
After looking more, this may be caused by the bootstrap arcade version.  It may need to be updated to pick up these changes - https://github.com/dotnet/arcade/commit/c0c425d9b85b125bbaf59581639355f1d2b99149

**Comment by MichaelSimons** [comment]
cc @ViktorHofer for awareness

**Comment by mthalman** [comment]
Ah, yeah. That makes sense.

@ellahathaway - I suspect that these prebuilts will be resolved when I re-bootstrap the VMR (needed to resolve https://github.com/dotnet/source-build/issues/3815). That will cause a newer version of Arcade to be used when building the VMR's Arcade.

**Comment by ellahathaway** [comment]
@mthalman Sounds good! I will close this PR.

**Pull request closed without merging**
